name: Build and Release Go Program

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: make

      - name: Upload build assets
        uses: actions/upload-artifact@v3
        with:
          name: build-assets
          path: ./build

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build assets
        uses: actions/download-artifact@v2
        with:
          name: build-assets
          path: ./build

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create GitHub Release
        id: create_release
        run: |
          gh release create ${GITHUB_REF##*/} ./build/* --title "Release ${{ github.ref }}" --notes "Release notes for ${{ github.ref }}"
